package com.lv.bean.sitech;


import com.lv.bean.sitech.OsMsgAlarmInst;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OsMsgAlarmInstExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public OsMsgAlarmInstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample page(Integer page, Integer pageSize) {
        this.offset = (page - 1) * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        OsMsgAlarmInstExample example = new OsMsgAlarmInstExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public OsMsgAlarmInstExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMsgAlarmInstIdIsNull() {
            addCriterion("msg_alarm_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdIsNotNull() {
            addCriterion("msg_alarm_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdEqualTo(Long value) {
            addCriterion("msg_alarm_inst_id =", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdNotEqualTo(Long value) {
            addCriterion("msg_alarm_inst_id <>", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdGreaterThan(Long value) {
            addCriterion("msg_alarm_inst_id >", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdGreaterThanOrEqualTo(Long value) {
            addCriterion("msg_alarm_inst_id >=", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdLessThan(Long value) {
            addCriterion("msg_alarm_inst_id <", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdLessThanOrEqualTo(Long value) {
            addCriterion("msg_alarm_inst_id <=", value, "msgAlarmInstId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMsgAlarmInstIdLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("msg_alarm_inst_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdIn(List<Long> values) {
            addCriterion("msg_alarm_inst_id in", values, "msgAlarmInstId");
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdNotIn(List<Long> values) {
            addCriterion("msg_alarm_inst_id not in", values, "msgAlarmInstId");
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdBetween(Long value1, Long value2) {
            addCriterion("msg_alarm_inst_id between", value1, value2, "msgAlarmInstId");
            return (Criteria) this;
        }

        public Criteria andMsgAlarmInstIdNotBetween(Long value1, Long value2) {
            addCriterion("msg_alarm_inst_id not between", value1, value2, "msgAlarmInstId");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNull() {
            addCriterion("busi_type is null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIsNotNull() {
            addCriterion("busi_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusiTypeEqualTo(String value) {
            addCriterion("busi_type =", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotEqualTo(String value) {
            addCriterion("busi_type <>", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThan(String value) {
            addCriterion("busi_type >", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("busi_type >=", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThan(String value) {
            addCriterion("busi_type <", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeLessThanOrEqualTo(String value) {
            addCriterion("busi_type <=", value, "busiType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiTypeLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiTypeLike(String value) {
            addCriterion("busi_type like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotLike(String value) {
            addCriterion("busi_type not like", value, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeIn(List<String> values) {
            addCriterion("busi_type in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotIn(List<String> values) {
            addCriterion("busi_type not in", values, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeBetween(String value1, String value2) {
            addCriterion("busi_type between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiTypeNotBetween(String value1, String value2) {
            addCriterion("busi_type not between", value1, value2, "busiType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeIsNull() {
            addCriterion("busi_sub_type is null");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeIsNotNull() {
            addCriterion("busi_sub_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeEqualTo(String value) {
            addCriterion("busi_sub_type =", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeNotEqualTo(String value) {
            addCriterion("busi_sub_type <>", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeGreaterThan(String value) {
            addCriterion("busi_sub_type >", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeGreaterThanOrEqualTo(String value) {
            addCriterion("busi_sub_type >=", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeLessThan(String value) {
            addCriterion("busi_sub_type <", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeLessThanOrEqualTo(String value) {
            addCriterion("busi_sub_type <=", value, "busiSubType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiSubTypeLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_sub_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeLike(String value) {
            addCriterion("busi_sub_type like", value, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeNotLike(String value) {
            addCriterion("busi_sub_type not like", value, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeIn(List<String> values) {
            addCriterion("busi_sub_type in", values, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeNotIn(List<String> values) {
            addCriterion("busi_sub_type not in", values, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeBetween(String value1, String value2) {
            addCriterion("busi_sub_type between", value1, value2, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiSubTypeNotBetween(String value1, String value2) {
            addCriterion("busi_sub_type not between", value1, value2, "busiSubType");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoIsNull() {
            addCriterion("busi_order_no is null");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoIsNotNull() {
            addCriterion("busi_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoEqualTo(String value) {
            addCriterion("busi_order_no =", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoNotEqualTo(String value) {
            addCriterion("busi_order_no <>", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoGreaterThan(String value) {
            addCriterion("busi_order_no >", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("busi_order_no >=", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoLessThan(String value) {
            addCriterion("busi_order_no <", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoLessThanOrEqualTo(String value) {
            addCriterion("busi_order_no <=", value, "busiOrderNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andBusiOrderNoLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("busi_order_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoLike(String value) {
            addCriterion("busi_order_no like", value, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoNotLike(String value) {
            addCriterion("busi_order_no not like", value, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoIn(List<String> values) {
            addCriterion("busi_order_no in", values, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoNotIn(List<String> values) {
            addCriterion("busi_order_no not in", values, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoBetween(String value1, String value2) {
            addCriterion("busi_order_no between", value1, value2, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andBusiOrderNoNotBetween(String value1, String value2) {
            addCriterion("busi_order_no not between", value1, value2, "busiOrderNo");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateIsNull() {
            addCriterion("should_send_date is null");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateIsNotNull() {
            addCriterion("should_send_date is not null");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateEqualTo(Date value) {
            addCriterion("should_send_date =", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateNotEqualTo(Date value) {
            addCriterion("should_send_date <>", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateGreaterThan(Date value) {
            addCriterion("should_send_date >", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateGreaterThanOrEqualTo(Date value) {
            addCriterion("should_send_date >=", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateLessThan(Date value) {
            addCriterion("should_send_date <", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateLessThanOrEqualTo(Date value) {
            addCriterion("should_send_date <=", value, "shouldSendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andShouldSendDateLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("should_send_date <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andShouldSendDateIn(List<Date> values) {
            addCriterion("should_send_date in", values, "shouldSendDate");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateNotIn(List<Date> values) {
            addCriterion("should_send_date not in", values, "shouldSendDate");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateBetween(Date value1, Date value2) {
            addCriterion("should_send_date between", value1, value2, "shouldSendDate");
            return (Criteria) this;
        }

        public Criteria andShouldSendDateNotBetween(Date value1, Date value2) {
            addCriterion("should_send_date not between", value1, value2, "shouldSendDate");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNull() {
            addCriterion("send_flag is null");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNotNull() {
            addCriterion("send_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSendFlagEqualTo(String value) {
            addCriterion("send_flag =", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagNotEqualTo(String value) {
            addCriterion("send_flag <>", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThan(String value) {
            addCriterion("send_flag >", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("send_flag >=", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThan(String value) {
            addCriterion("send_flag <", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThanOrEqualTo(String value) {
            addCriterion("send_flag <=", value, "sendFlag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendFlagLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_flag <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendFlagLike(String value) {
            addCriterion("send_flag like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotLike(String value) {
            addCriterion("send_flag not like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagIn(List<String> values) {
            addCriterion("send_flag in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotIn(List<String> values) {
            addCriterion("send_flag not in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagBetween(String value1, String value2) {
            addCriterion("send_flag between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotBetween(String value1, String value2) {
            addCriterion("send_flag not between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendDateIsNull() {
            addCriterion("send_date is null");
            return (Criteria) this;
        }

        public Criteria andSendDateIsNotNull() {
            addCriterion("send_date is not null");
            return (Criteria) this;
        }

        public Criteria andSendDateEqualTo(Date value) {
            addCriterion("send_date =", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateNotEqualTo(Date value) {
            addCriterion("send_date <>", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateGreaterThan(Date value) {
            addCriterion("send_date >", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateGreaterThanOrEqualTo(Date value) {
            addCriterion("send_date >=", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateLessThan(Date value) {
            addCriterion("send_date <", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateLessThanOrEqualTo(Date value) {
            addCriterion("send_date <=", value, "sendDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSendDateLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("send_date <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSendDateIn(List<Date> values) {
            addCriterion("send_date in", values, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotIn(List<Date> values) {
            addCriterion("send_date not in", values, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateBetween(Date value1, Date value2) {
            addCriterion("send_date between", value1, value2, "sendDate");
            return (Criteria) this;
        }

        public Criteria andSendDateNotBetween(Date value1, Date value2) {
            addCriterion("send_date not between", value1, value2, "sendDate");
            return (Criteria) this;
        }

        public Criteria andTmpCodeIsNull() {
            addCriterion("tmp_code is null");
            return (Criteria) this;
        }

        public Criteria andTmpCodeIsNotNull() {
            addCriterion("tmp_code is not null");
            return (Criteria) this;
        }

        public Criteria andTmpCodeEqualTo(String value) {
            addCriterion("tmp_code =", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeNotEqualTo(String value) {
            addCriterion("tmp_code <>", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeGreaterThan(String value) {
            addCriterion("tmp_code >", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tmp_code >=", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeLessThan(String value) {
            addCriterion("tmp_code <", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeLessThanOrEqualTo(String value) {
            addCriterion("tmp_code <=", value, "tmpCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpCodeLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_code <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpCodeLike(String value) {
            addCriterion("tmp_code like", value, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpCodeNotLike(String value) {
            addCriterion("tmp_code not like", value, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpCodeIn(List<String> values) {
            addCriterion("tmp_code in", values, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpCodeNotIn(List<String> values) {
            addCriterion("tmp_code not in", values, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpCodeBetween(String value1, String value2) {
            addCriterion("tmp_code between", value1, value2, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpCodeNotBetween(String value1, String value2) {
            addCriterion("tmp_code not between", value1, value2, "tmpCode");
            return (Criteria) this;
        }

        public Criteria andTmpContentIsNull() {
            addCriterion("tmp_content is null");
            return (Criteria) this;
        }

        public Criteria andTmpContentIsNotNull() {
            addCriterion("tmp_content is not null");
            return (Criteria) this;
        }

        public Criteria andTmpContentEqualTo(String value) {
            addCriterion("tmp_content =", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentNotEqualTo(String value) {
            addCriterion("tmp_content <>", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentGreaterThan(String value) {
            addCriterion("tmp_content >", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentGreaterThanOrEqualTo(String value) {
            addCriterion("tmp_content >=", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentLessThan(String value) {
            addCriterion("tmp_content <", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentLessThanOrEqualTo(String value) {
            addCriterion("tmp_content <=", value, "tmpContent");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTmpContentLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("tmp_content <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTmpContentLike(String value) {
            addCriterion("tmp_content like", value, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andTmpContentNotLike(String value) {
            addCriterion("tmp_content not like", value, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andTmpContentIn(List<String> values) {
            addCriterion("tmp_content in", values, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andTmpContentNotIn(List<String> values) {
            addCriterion("tmp_content not in", values, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andTmpContentBetween(String value1, String value2) {
            addCriterion("tmp_content between", value1, value2, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andTmpContentNotBetween(String value1, String value2) {
            addCriterion("tmp_content not between", value1, value2, "tmpContent");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateDateLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("create_date <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andNoteLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("note <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andServLoginNoIsNull() {
            addCriterion("serv_login_no is null");
            return (Criteria) this;
        }

        public Criteria andServLoginNoIsNotNull() {
            addCriterion("serv_login_no is not null");
            return (Criteria) this;
        }

        public Criteria andServLoginNoEqualTo(String value) {
            addCriterion("serv_login_no =", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoNotEqualTo(String value) {
            addCriterion("serv_login_no <>", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoGreaterThan(String value) {
            addCriterion("serv_login_no >", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoGreaterThanOrEqualTo(String value) {
            addCriterion("serv_login_no >=", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoLessThan(String value) {
            addCriterion("serv_login_no <", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoLessThanOrEqualTo(String value) {
            addCriterion("serv_login_no <=", value, "servLoginNo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServLoginNoLessThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_login_no <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServLoginNoLike(String value) {
            addCriterion("serv_login_no like", value, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServLoginNoNotLike(String value) {
            addCriterion("serv_login_no not like", value, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServLoginNoIn(List<String> values) {
            addCriterion("serv_login_no in", values, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServLoginNoNotIn(List<String> values) {
            addCriterion("serv_login_no not in", values, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServLoginNoBetween(String value1, String value2) {
            addCriterion("serv_login_no between", value1, value2, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServLoginNoNotBetween(String value1, String value2) {
            addCriterion("serv_login_no not between", value1, value2, "servLoginNo");
            return (Criteria) this;
        }

        public Criteria andServNumberIsNull() {
            addCriterion("serv_number is null");
            return (Criteria) this;
        }

        public Criteria andServNumberIsNotNull() {
            addCriterion("serv_number is not null");
            return (Criteria) this;
        }

        public Criteria andServNumberEqualTo(String value) {
            addCriterion("serv_number =", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberNotEqualTo(String value) {
            addCriterion("serv_number <>", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberNotEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberGreaterThan(String value) {
            addCriterion("serv_number >", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberGreaterThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberGreaterThanOrEqualTo(String value) {
            addCriterion("serv_number >=", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberGreaterThanOrEqualToColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberLessThan(String value) {
            addCriterion("serv_number <", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberLessThanColumn(com.lv.bean.sitech.OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberLessThanOrEqualTo(String value) {
            addCriterion("serv_number <=", value, "servNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andServNumberLessThanOrEqualToColumn(OsMsgAlarmInst.Column column) {
            addCriterion(new StringBuilder("serv_number <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andServNumberLike(String value) {
            addCriterion("serv_number like", value, "servNumber");
            return (Criteria) this;
        }

        public Criteria andServNumberNotLike(String value) {
            addCriterion("serv_number not like", value, "servNumber");
            return (Criteria) this;
        }

        public Criteria andServNumberIn(List<String> values) {
            addCriterion("serv_number in", values, "servNumber");
            return (Criteria) this;
        }

        public Criteria andServNumberNotIn(List<String> values) {
            addCriterion("serv_number not in", values, "servNumber");
            return (Criteria) this;
        }

        public Criteria andServNumberBetween(String value1, String value2) {
            addCriterion("serv_number between", value1, value2, "servNumber");
            return (Criteria) this;
        }

        public Criteria andServNumberNotBetween(String value1, String value2) {
            addCriterion("serv_number not between", value1, value2, "servNumber");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private OsMsgAlarmInstExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(OsMsgAlarmInstExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public OsMsgAlarmInstExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table os_msg_alarm_inst
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void criteria(Criteria criteria);
    }

    /**
     * This interface was generated by MyBatis Generator.
     * This interface corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table os_msg_alarm_inst
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        void example(OsMsgAlarmInstExample example);
    }
}