server:
  port: 8899

lvmh:
  test:
    testJob:
      false

friends:
  name:zhangsan
  age:20

pet:
  - dog
  - pig
  - cat
logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/untitledtest
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
