server:
  port: 8899

lvmh:
  test:
    testJob:
      false

friends:
  name:zhangsan
  age:20

pet:
  - dog
  - pig
  - cat
logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.goldendb.jdbc.Driver
    url: jdbc:goldendb://172.18.196.229:8880/oscomadm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: oscomadmopr
    password: oscomadmopr1@3$
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.2.129
    port: 6379
    timeout: 1000
    database: 0
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

file :
  upload:
    path: F:\\upload