server:
  port: 8899

lvmh:
  test:
    testJob:
      false

friends:
  name:zhangsan
  age:20

pet:
  - dog
  - pig
  - cat
logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/untitledtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.2.129
    port: 6379
    timeout: 1000
    database: 0
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

files:
  upload:
    path:'/uploadFile'