package com.lv.dao.mapper;

import com.lv.bean.sitech.OsMsgAlarmInst;
import com.lv.bean.sitech.OsMsgAlarmInstExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OsMsgAlarmInstMapper {
    int deleteByExample(OsMsgAlarmInstExample example);

    int deleteByPrimaryKey(Long msgAlarmInstId);

    int insert(OsMsgAlarmInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") OsMsgAlarmInst record, @Param("selective") OsMsgAlarmInst.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OsMsgAlarmInst selectByPrimaryKeySelective(@Param("msgAlarmInstId") Long msgAlarmInstId, @Param("selective") OsMsgAlarmInst.Column ... selective);

    OsMsgAlarmInst selectByPrimaryKey(Long msgAlarmInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") OsMsgAlarmInst record, @Param("example") OsMsgAlarmInstExample example, @Param("selective") OsMsgAlarmInst.Column ... selective);

    int updateByExample(@Param("record") OsMsgAlarmInst record, @Param("example") OsMsgAlarmInstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") OsMsgAlarmInst record, @Param("selective") OsMsgAlarmInst.Column ... selective);

    int updateByPrimaryKey(OsMsgAlarmInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OsMsgAlarmInst> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table os_msg_alarm_inst
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OsMsgAlarmInst> list, @Param("selective") OsMsgAlarmInst.Column ... selective);
}