package com.lv.bean.mapper;

import com.lv.bean.entity.FileRel;
import com.lv.bean.entity.FileRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileRelMapper {
    int deleteByExample(FileRelExample example);

    int deleteByPrimaryKey(String relId);

    int insert(FileRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") FileRel record, @Param("selective") FileRel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileRel selectOneByExample(FileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileRel selectOneByExampleSelective(@Param("example") FileRelExample example, @Param("selective") FileRel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FileRel> selectByExampleSelective(@Param("example") FileRelExample example, @Param("selective") FileRel.Column ... selective);

    List<FileRel> selectByExample(FileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileRel selectByPrimaryKeySelective(@Param("relId") String relId, @Param("selective") FileRel.Column ... selective);

    FileRel selectByPrimaryKey(String relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") FileRel record, @Param("example") FileRelExample example, @Param("selective") FileRel.Column ... selective);

    int updateByExample(@Param("record") FileRel record, @Param("example") FileRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_rel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") FileRel record, @Param("selective") FileRel.Column ... selective);

    int updateByPrimaryKey(FileRel record);
}