package com.lv.bean.mapper;

import com.lv.bean.entity.FileInfo;
import com.lv.bean.entity.FileInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileInfoMapper {
    long countByExample(FileInfoExample example);

    int deleteByExample(FileInfoExample example);

    int deleteByPrimaryKey(String fileId);

    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") FileInfo record, @Param("selective") FileInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileInfo selectOneByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileInfo selectOneByExampleSelective(@Param("example") FileInfoExample example, @Param("selective") FileInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FileInfo> selectByExampleSelective(@Param("example") FileInfoExample example, @Param("selective") FileInfo.Column ... selective);

    List<FileInfo> selectByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileInfo selectByPrimaryKeySelective(@Param("fileId") String fileId, @Param("selective") FileInfo.Column ... selective);

    FileInfo selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") FileInfo record, @Param("example") FileInfoExample example, @Param("selective") FileInfo.Column ... selective);

    int updateByExample(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") FileInfo record, @Param("selective") FileInfo.Column ... selective);

    int updateByPrimaryKey(FileInfo record);
}